USE [master]
GO

/****** Object:  Database [projektHi]    Script Date: 17.04.2021 17:49:43 ******/
CREATE DATABASE [projektHi]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'projektHi', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLW\MSSQL\DATA\projektHi.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'projektHi_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLW\MSSQL\DATA\projektHi_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [projektHi].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [projektHi] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [projektHi] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [projektHi] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [projektHi] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [projektHi] SET ARITHABORT OFF 
GO

ALTER DATABASE [projektHi] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [projektHi] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [projektHi] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [projektHi] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [projektHi] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [projektHi] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [projektHi] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [projektHi] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [projektHi] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [projektHi] SET  DISABLE_BROKER 
GO

ALTER DATABASE [projektHi] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [projektHi] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [projektHi] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [projektHi] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [projektHi] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [projektHi] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [projektHi] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [projektHi] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [projektHi] SET  MULTI_USER 
GO

ALTER DATABASE [projektHi] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [projektHi] SET DB_CHAINING OFF 
GO

ALTER DATABASE [projektHi] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [projektHi] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [projektHi] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [projektHi] SET  READ_WRITE 
GO


